apiVersion: v1
stringData:
  automation-secret-token: $automation_secret_token
  gemini-api-key: $gemini_api_key
  github-token: $github_token
  jira-api-token: $jira_api_token
  jira-webhook-secret: $jira_webhook_secret
kind: Secret
metadata:
  name: ssqe-orchestrator
  namespace: finoptix-ns
type: Opaque